[global]
repo1-type=s3
repo1-path=/backups/postgresql
repo1-s3-bucket=__R2_BUCKET__
repo1-s3-endpoint=__R2_S3_ENDPOINT__
repo1-s3-region=auto
repo1-s3-key=__R2_ACCESS_KEY_ID__
repo1-s3-key-secret=__R2_SECRET_ACCESS_KEY__
repo1-s3-uri-style=path
repo1-s3-verify-tls=y
repo1-retention-full=7
repo1-retention-diff=28
archive-async=y
spool-path=/var/spool/pgbackrest
process-max=2
compress-type=zst
start-fast=y
log-level-console=info

[crm-barcode]
pg1-path=/var/lib/postgresql/data
pg1-port=5432
pg1-socket-path=/var/run/postgresql
